### ISSUE TITLE
Educational Page

### ISSUE THREAD

**Issue by Insax** [savetheinternetinfo/website#10]
Add Videos Newspapers / Blogs with good explanations of the problem to a subpage - contact Public Relations to get your information

**Comment by Pacerino** [comment]
Currently on hold because missing external informations

**Comment by Pacerino** [comment]
Issue is held because information and use case are missing.
Will hold agreement with overall coordination.

**Comment by kellerrennkadse** [comment]
That's basically a duplicate of #70 right?

**Comment by kellerrennkadse** [comment]
This is already done (even if its gross af, but PR refuses to provide data to fix this.)
