### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by NLDev** [savetheinternetinfo/website#100]
Info: Proposal from **Norris**

**Describe the solution you'd like:**
We need a basic contact form for ideas, suggestions, inspirations, etc.
Generally suggestions for various strategies. 
But **not** for any kind of criticism related to team-internal things. 

In conclusion:
A basic Text-only contact form which sends the text to an email address upon submission. 

**Additional context:**
The contact form should be secured against spam-bots.

**Comment by Pacerino** [comment]
First version can be found here (ಡ_ಡ)☞ [feature/contact-form](https://github.com/savetheinternetinfo/website/tree/feature/contact-form)

Currently the whole backend stuff is missing. Will be done later ☜(꒡⌓꒡)

**Comment by Pacerino** [comment]
Before I forget: You need an API key for Google reCAPTCHA!
ヽ(｀Д´)⊃━☆ﾟ. * ･ ｡ﾟ, https://www.google.com/recaptcha/intro/

**Comment by Pacerino** [comment]
#106 
Pull Request is open!

**Comment by NLDev** [comment]
Resolved by https://github.com/savetheinternetinfo/website/pull/106
