### ISSUE TITLE
Missing Tailwindcss Classes and Helper

### ISSUE THREAD

**Issue by Pacerino** [savetheinternetinfo/website#105]
**Describe the bug**
Some important css classes and helpers are missing in tailwind. Example `.text-red`

**To Reproduce**
1. Use `.text-red` on Text

**Expected behavior**
The text should be red

**Additional context**
These classes are important for futher issues like the contact form

**Comment by NLDev** [comment]
https://github.com/savetheinternetinfo/website/blob/develop/tailwind-config.js#L58-L138

**Comment by Pacerino** [comment]
Closed. Fixed in the contact form branch
