### ISSUE TITLE
Implement map for STI Action Day

### ISSUE THREAD

**Issue by NLDev** [savetheinternetinfo/website#115]
**Is your feature request related to a problem? Please describe.**
Proposal from horsthansen: We need to build a ~wall~ _map_

**Describe the solution you'd like**
A small info text on the main page with a map (and locations) next to it.
Once clicked on the map, the user gets redirected to a subsite (/actionday for instance).
The subsite should look like [saveyourinternet.today](https://saveyourinternet.today)

**Describe alternatives you've considered**
There are no alternatives. **NONE**. **Z E R O**. **`N U L L`**. 
PR annoyed me with this for three days straight.

**Additional context**
I'm scared because horst will hit me if I we don't implement that ASAP.

**Comment by Pacerino** [comment]
If Horst beats you, I'll beat him!
Do you need anything Frontend Technically?

**Comment by Pacerino** [comment]
LeafletJS? I could help because I already have experience with LeafletJS. Otherwise, I offer my help gladly.
________________________________

**Comment by NLDev** [comment]
I've never worked with that, but it looks amazing! I'd def use that. 

And thanks pac <3 

Insax and I are currently unavailable. I still try to do as much as I can. For the map on the subsite, we can probably use the code from saveyourinternet.today as it is, since its open source and licensed under GNU AFFERNO. I already sent a mail to the main developer to discuss the terms under which we can use the code. If its not too much work to build the map without using saveyourinternet's code, we can just use the data:

https://umap.openstreetmap.fr/en/datalayer/608593/

This is the whole map:

https://umap.openstreetmap.fr/en/map/copyright-action-day-2018_238803#5/51.331/9.031

**Comment by horsthansen** [comment]
A small info text=3-4 sentences which describe why and call for action.

**Comment by Pacerino** [comment]
Give me the text. I will not write my own text.

**Comment by horsthansen** [comment]
Text is now ready, if too long, tell me:
Von den Befürwortern der Urherberrechtsreform im digitalen Binnenmarkt wird behauptet, all die E-Mails und Unterschriften seien von Bots generiert und verschickt worden.  Damit nehmen sie den Bürgerwillen der fast 1.000.000 Unterzeichner unserer Petition nicht ernst.
Zeigen wir ihnen, wie gelebte Demokratie funktioniert!
Schau auf der Karte nach Demos in deiner Nähe. Zeigen wir ihnen, dass wir keine Bots sind. Zeigen wir, dass wir reale Menschensind, die gegen diese Richtlinie demonstrieren.
Du findest kein Kreuz in deiner Nähe? Dann melde doch einfach selbst eine Demonstration an!
Sorgen wir dafür, dass die Befürworter unsere Bewegung nicht mehr als Bots schönreden können, sondern gezwungen sind, im Sinne der Menschen zu handeln!
