### ISSUE TITLE
Scrollen klappt nicht wenn Map den Bildschirm für sich beansprucht

### ISSUE THREAD

**Issue by Pacerino** [savetheinternetinfo/website#128]
**Describe the bug**
Wenn die Karte auf Mobiltelefonen einfach den gesamten Bildschirm beansprucht gibt es nicht mehr die Möglichkeit zu Scrollen da sobald man auf der Karte nach oben oder unten zieht sich nur die Karte bewegt

**To Reproduce**
1. Geh auf /actionday mit deinem Handy
2. Drehe dein Handy oder wie auch immer so dass die Karte dein gesamten Bildschirm beansprucht
3. Versuch zu Scrollen
4. ???
5. Profit?

**Expected behavior**
Scrollen! ICH WILL SCROLLEN KÖNNEN!

**Screenshots**
![vivaldi_2018-08-26_03-19-17](https://user-images.githubusercontent.com/22194063/44623952-e865ec80-a8de-11e8-850b-4e63ecd66fa2.png)

**Smartphone (please complete the following information):**
 - Device: [Jedes Handy bei der die Karte einfach _ALLES_ beansprucht]

**Additional context**
`!important` ist _*KEINE*_ Lösung!

**Comment by Pacerino** [comment]
Not my problem. I have tried to solve it but will not work on it due to another "error". This issue can drink bleaching as long as it pleases. I'm not interested

**Comment by NLDev** [comment]
Well, that's indeed an issue. 
I guess we need to get some more frontend-devs to join our team then. 😸

**Comment by NLDev** [comment]
Map will be removed in aprox one or two days.
