### ISSUE TITLE
neuer reiter "Sti-action day"

### ISSUE THREAD

**Issue by Quallini** [savetheinternetinfo/website#131]
**Is your feature request related to a problem? Please describe.**
kein problem

**Describe the solution you'd like**
bitte eine neuen reiter auf der webseite einfügen, darunter soll dann die karte wiederzufinden sein, die soll von der startseiten weg. dazu kommt noch ein text. sobald der da ist, wir der nachgeliefert. 
**Describe alternatives you've considered**
ihr könnt das schonmal auslagern und den aktuellen stand wie auf der startseite nehmen

**Additional context**

**Comment by NLDev** [comment]
Resolved by https://github.com/savetheinternetinfo/website/pull/135
