### ISSUE TITLE
Update Startseite

### ISSUE THREAD

**Issue by Quallini** [savetheinternetinfo/website#132]
**Is your feature request related to a problem? Please describe.**
nein
aber tut mir leid, dass dieser auftrag von meiner seite so ne halbe baustelle ist. 
**Describe the solution you'd like**
Anstatt der karte und dem text wird der text ersetzt. link unten zu text. grafik folgt. Formatierung Text links udn Bild rechts bitte beibehalten

**Describe alternatives you've considered**

**Additional context**
https://cryptpad.fr/pad/#/2/pad/edit/-LFa10m0CuQjLx2ov1BLr+fs/ unter "Webseite"

**Comment by NLDev** [comment]
Resolved by https://github.com/savetheinternetinfo/website/pull/135
