### ISSUE TITLE
"Article 3 in detail" should be 13

### ISSUE THREAD

**Issue by picuber** [savetheinternetinfo/website#188]
**Describe the bug**
On the start page at the bottom it says "Article 3 in detail" in a heading, but it should say "Article 13 in detail".

**To Reproduce**
1. Go to https://safetheinternet.info/
2. Scroll down to the bottom
3. See error

**Expected behavior**
It should say "Article 13 in detail".

**Screenshots**
https://imgur.com/a/pqqTWsv

**Additional context**
This happens in every language.

**Comment by NLDev** [comment]
Thank you for the issue!

The paragraph below is actually about Article 3, not 13. More info here: https://juliareda.eu/eu-copyright-reform/text-and-data-mining/

We are going to make this more clear soon! :)

**Comment by picuber** [comment]
Oh, I see. Thanks for the notice.
One thing I want to note then would be the corresponding item names for those text elements in the scr/language files:

index_art13_title
index_art13_content

which added to this confusion.

Cheers

**Comment by NLDev** [comment]
Thanks for the heads up! 

We'll fix that in the next update ^^

**Comment by NLDev** [comment]
Notations in the code have been updated accordingly:
https://github.com/savetheinternetinfo/website/commit/86f0e13129a00c6670f51a515bdded113878b293
