### ISSUE TITLE
Making TypeScript a local dependency

### ISSUE THREAD

**Issue by aequabit** [savetheinternetinfo/website#23]
Is there a reason why we are installing TypeScript globally? If not, we should make it a local dependency.

**Comment by NLDev** [comment]
For the TS code in the backend we do not use a TS Loader, but use TSC directly. 
In other words, if you want to compile the backend, you need TypeScript installed globally. 
For this JS files in [/assets/js/](https://github.com/savetheinternetinfo/website/tree/develop/src/assets/js) this is not required.

**Comment by aequabit** [comment]
You could just make it a local dependency and run `npx tsc` or `node_modules/.bin/tsc`.
