### ISSUE TITLE
Simple search bar for the demonstration map

### ISSUE THREAD

**Issue by sinnlosername** [savetheinternetinfo/website#305]
**Is your feature request related to a problem? Please describe.**
When you want to check out the estimated routes to different demonstrations you always need to copy each nearby demonstration location into google maps and calculate the route there. Imagine you got 5 friends spread across germany and you want to determine which location would be the best to meet for everyone.

**Describe the solution you'd like**
It would be great to have a search bar where you can enter your address and it will then calculate the route on open street maps to the closed (or a selected) demonstration.

**Comment by NLDev** [comment]
Sorry for the late response but other things had priority. 
Since the demos officially end in three days, that's not worth implementing anymore.
