### ISSUE TITLE
Missing grafik in the top

### ISSUE THREAD

**Issue by geisterfurz007** [savetheinternetinfo/website#322]
**Describe the bug**
When visiting https://savetheinternet.info/demos the animated image in the top is missing.

**To Reproduce**
1. Go to 'https://savetheinternet.info/demos'
2. See error

**Expected behavior**
The image should appear in the top like this:
![grafik](https://user-images.githubusercontent.com/26303198/54707058-90275e00-4b40-11e9-91b8-0854487659a1.png)

Note that in the screenshot above the URL contains a quote (see #306)
Without the quote, the page looks like this:

**Screenshots**
![grafik](https://user-images.githubusercontent.com/26303198/54707162-c1079300-4b40-11e9-8765-b781d99323f5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser Firefox
 - Version 66.0

**Additional context**
The console shows: `document.getElementById(...) is null`.  
This does not happen on the URL with the quote added.

![grafik](https://user-images.githubusercontent.com/26303198/54707218-e5fc0600-4b40-11e9-85ca-8d89f4b61af0.png)

**Comment by jonas32** [comment]
#323 
Thank you!
