### ISSUE TITLE
updating languages

### ISSUE THREAD

**Issue by jsirsch** [savetheinternetinfo/website#36]
**branch:** feature/translations
**content:** https://savetheinternet.piratenpad.de/176?
**task:**
update fields of the following languages:
- [x] cn.json
- [x] de.json
- [x] dk.json
- [x] en.json
- [x] es.json
- [ ] fi.json
- [x] fr.json
- [x] it.json
- [ ] nl.json
- [ ] pl.json
- [x] se.json

**fields:**
article_title
article_content

about_sub_title2
about_sub_text2_1

about_sub_title5
about_sub_text5_1

**Comment by aytic** [comment]
https://github.com/savetheinternetinfo/translation/tree/master/translations/schema-08a58462
New translation JASON (jk) files can be found above.

**Comment by aytic** [comment]
Chinese landing page done (I think we can keep about us in english)

**Comment by NLDev** [comment]
Closing since no new languages are going to be implemented for now. 

Same goes for https://github.com/savetheinternetinfo/website/issues/38
