### ISSUE TITLE
Important corrections in danish translation

### ISSUE THREAD

**Issue by schnapsdrossel** [savetheinternetinfo/website#38]
[data-dk-latest new.zip](https://github.com/savetheinternetinfo/website/files/2130450/data-dk-latest.new.zip)

**Comment by jsirsch** [comment]
**Issue:** Corrections get not displayed in page!

<img width="1920" alt="bildschirmfoto 2018-06-25 um 11 41 26" src="https://user-images.githubusercontent.com/26800988/41843148-0b664ba0-786d-11e8-80d7-c7238b0ec680.png">

**Comment by jsirsch** [comment]
Version conflict in "about_sub_text2_1" from https://savetheinternet.piratenpad.de/176:
"Den 4. juli vil EU-Parlamentet stille skærpelsen af ophavsretten til sidste afstemning. Dette vil medføre store ændringer i ophavsretten, som kan være en større belastning for alle, i stedet for at være en aflastning."
vs.
Den 4. juli vil EU-Parlamentet stille skærpelsen af ophavsretten til sidste afstemning. Dette vil medføre **en** store ændringer i ophavsretten, som kan være en større belastning for alle, i stedet for at være en aflastning.

Please review @schnapsdrossel.

**Comment by NLDev** [comment]
Closing since no new languages are going to be implemented for now. 

Same goes for https://github.com/savetheinternetinfo/website/issues/36
