### ISSUE TITLE
Wrong z-index in Gallery

### ISSUE THREAD

**Issue by jsirsch** [savetheinternetinfo/website#59]
**Bug:**
The z-index of the overlay which contains the detail view of the galery image and some control elements is wrong. It is set to 1040, but an overlay has the value 1050, so it is to low. I suggest to increase the value to 1060. The Element has the following classes: class="sl-wrapper simple-lightbox".

**Screenshots**
Before:
<img width="945" alt="bildschirmfoto 2018-06-29 um 22 11 43" src="https://user-images.githubusercontent.com/26800988/42112856-90bdae18-7be9-11e8-83fc-e91876270eff.png">
After:
<img width="950" alt="bildschirmfoto 2018-06-29 um 22 12 01" src="https://user-images.githubusercontent.com/26800988/42112861-92e8d5aa-7be9-11e8-8245-2999a094b5d1.png">

**Comment by jsirsch** [comment]
It looks like two classes have been confused:
<img width="443" alt="bildschirmfoto 2018-06-29 um 22 37 35" src="https://user-images.githubusercontent.com/26800988/42113892-4a676b3a-7bed-11e8-8d5a-86168af65470.png">

**Comment by jsirsch** [comment]
It seems like all z-indexes are right and equal to the example in the npm folder, but for some reason, the problem is still there.

**Comment by jsirsch** [comment]
After a lot of analysis, I am quite sure that the problem is not within the HTML in "gallery.ejs". I included parts from the example in the npm folder of "simplelightbox" to check if we have a problem with the automatically including of pictures through EJS. That isn't the case. A very simple clip from the example is still not working as expected. So I suppose the problem could be connected to the usage of typescript, jquery, importing of the dependencies or some timing issues etc.

**Comment by jsirsch** [comment]
Loading and function of simplelightbox js dependencies works also properly.
Because of that, the issue is probably a conflict between different CSS commands. I assume that some global SCSS code or code from different frameworks are not compatible with the simplelightbox dependency.

**Comment by jsirsch** [comment]
I localized a compatibility issue in the "@import "~tailwindcss/utilities";".
If this file isn't imported, the simplelightbox css is working correctly. But you also have to explude the following imports:
"
@import "shared";
@import "gallery";
@import "mep";
"
This is caused by the usage of "@apply".

**So now we must search for the compatibility issue in "tailwindcss/utilities". Do we need this import and the usage of the "@apply" statement?**
@NLDev @Crease29 @schrej @AmazingTurtle @Insax

**Comment by jsirsch** [comment]
Do we need the tailwind utilities? If that's the case, we need to use another npm package instead of the simplelightbox dependency.

**Comment by kellerrennkadse** [comment]
@jsirsch yep, we need the utilities.
There is no need to replace anything.. just fix the damn thing
