### ISSUE TITLE
reiter einbinden auf der webseite

### ISSUE THREAD

**Issue by Quallini** [savetheinternetinfo/website#62]
Als wir von der PR würden uns wünschen, wenn die Webseite auf den neusten Stand gebracht wird.
Zb stört mich persönlich der Link zu dem längst vergangen Lifestream zu der Sache im EU-Rat

Dann wäre es ganz toll, wenn man einzelne Reiter oder Verlinkungen zb zum Pressespiegel, zu einem Text zur Arbeit der Abgeordnetenwatch usw hinzufügen könnte

Die Daten dazu kommen dann halt von den Texter und uns. 
Wir freuen uns über euren Input dazu und eure Vorstellung davon, wie wir das zusammen zeitnah umsetzen können :)

**Comment by Insax** [comment]
http://dev.savetheinternet.info

Dann sollen die Texter aber mal gas geben - wir warten ausschließlich auf die weil viele übersetzungen falsch / mangelhaft sind.

**Comment by Quallini** [comment]
ja, aber zb den link zum livestream entfernen sollte ja schon möglich sein OHNE die texter ;)
und den pressespiegel bekommst du von mir, der ist in arbeit und gut vorangeschritten :) hab nur heute leider wenig personelle ressourcen in der pr heute. wir sind dran. hab ich pac gestern auch schon gesagt, der sollte euch liebste grüße von mir ausrichten.

**Comment by Insax** [comment]
Stream ist draußen - und es geht nicht nur um den pressespiegel - es geht um alle texte gesamt. Wir müssen nur das About-us und about fertig porten, dann ist das für uns erledigt.

**Comment by Quallini** [comment]
mein hirn hat grade total den link übersehen. die webseite sieht schonmal schön aus.
Was brauchst du konkret bei von mir und der PR zeitnah, dass ihr das schonmal einbinden könnt und so. Ich mach denen mal feuer unterm arsch

**Comment by Insax** [comment]
Die Texter und Übersetzer sollen 1x auf der Seite ordentlich korrekturlesen - wenn sie fehler finden können sie die dann direkt ausbessern und wir setzen uns dann dran und implementieren das.

**Comment by Quallini** [comment]
da musst du den texter ein dringendes ticket auf ost machen :D

**Comment by Quallini** [comment]
also: zu den Reitern.
Wir wünschen uns: 
-Abgeordnetenwatch
-Galerie (ja, die ist schon da, wäre es möglich, für jedes land da ne eigene zu machen. ich hab gesehen, die bilder sind ja eh schon nach sprache gelistet), so dass man nur "muttersprachlichen" content sieht?
-Pressespiegel (ist es möglich, das man da etwas programmiert, dass nach gängigen schlagwörtern wie "Artikel 13" selber was listet? ) oder müssen wir euch da quasi täglich ein update geben?
-Weiterführende Links
-Und ja, ich kümmer mich drum, dass ihr Inhalt bekommt :)
Die Reiter sind auch so mit Norris besprochen, die könnt ihr schonmal einbauen

**Comment by kellerrennkadse** [comment]
#68 #67 #66 #70
