### ISSUE TITLE
Reiter "Weiterführende Links"

### ISSUE THREAD

**Issue by Quallini** [savetheinternetinfo/website#68]
bitte ebenfalls zur Webseite hinzufügen

**Comment by Insax** [comment]
Bitte detaillierter beschreiben.

**Comment by Quallini** [comment]
Wie auch die anderen Reiter soll das Ein Reiter "Weiterführende Links" hin, damit wir da weiterführende Links zu wissenschaftlichen Arbeiten zum Thema usw veröffentlichen können

**Comment by kellerrennkadse** [comment]
Was ist hieraus jetzt eigentlich geworden @Pacerino
