### ISSUE TITLE
Reiter "Pressespiegel"

### ISSUE THREAD

**Issue by Quallini** [savetheinternetinfo/website#70]
Pressespiegel auf Webseite einfügen 
https://docs.google.com/spreadsheets/d/19WKHONdULFT3U8T-5dhguM5UgO71OzHAzwhZq1MKXaY/edit#gid=0
hier alle benötigten daten.
wäre schön wenn der "titel" auf den link verweisen würde und der link nicht extra aufgeführt wäre
ist es möglich einen code zu schreiben, dass der sich selber updatet?

**Comment by kellerrennkadse** [comment]
Eine bitte.. es gibt das Template "Feature Request" nicht ohne Grund.

![w3gelay 1](https://user-images.githubusercontent.com/40218022/42138388-17e752b0-7d7d-11e8-8a66-e47b989b007b.png)

**Comment by Quallini** [comment]
ich weiß nicht was du meinst :( ich bin kein nerd :(

**Comment by kellerrennkadse** [comment]
Wenn du auf "New Issue" klickst, bekommst du die Auswahl an Templates. Für neue Sachen bitte **Feature Request** ausfüllen (was da wohin muss steht ja im Text) und wenns Fehler gibt deb **Bug report** ausfüllen. 

Das macht es wesentlich übersichtlicher und leichter die Tickets zu bearbeiten, weil die Informationen dann vernünftig Strukturiert sind, und man das ganze auch priorisieren kann

**Comment by kellerrennkadse** [comment]
Dann darfst du eben nicht den gesamte vorgefertigten Text entfernen..
Im Prinzip ist das so aufgebaut:
```
**Hier steht die Frage**
[Hier kannst du darauf antworten]

**Nächste Frage**
[weitere antwort]
```

Wenn du das natürlich alles ersetzt bringt das nichts. Die Dinger zwischen `**` müssen stehen bleiben

**Comment by Quallini** [comment]
ah ja okay

**Comment by Pacerino** [comment]
Implement first version!

**TODO**

- [ ] Better Error handling

- [ ] Put config relevant values into the .env file

- [ ] Correction of the route

- [ ] Lint the whole implementation

Branch: [feature/press_review](https://github.com/savetheinternetinfo/website/tree/feature/press_review)
