### ISSUE TITLE
[FEATURE] Timeline

### ISSUE THREAD

**Issue by kellerrennkadse** [savetheinternetinfo/website#74]
**Is your feature request related to a problem? Please describe.**
Now that there have been multiple stages of the Copyright proposal, and there will be ongoing change until september, I'd like to have a way to represent that development

**Describe the solution you'd like**
I would like to implement some kind of timeline. From the first draft of the law, over the first and second vote etc, up to the point where there will be another vote.
We could link to information about those stages

**Describe alternatives you've considered**
Classic infotext (which might be more borign to read)

**Additional context**
Giving the visitors that kind of insight might engange them to inform themselves about that topic. 
Given that timeline, you can actually see that out protest had some serious effect on the outcome.

Example of a timeline I'd like to see: 
![timeline-template-4-1 1](https://user-images.githubusercontent.com/40218022/42320161-acd95592-8054-11e8-984d-47e69b989fbb.png)

**Comment by kellerrennkadse** [comment]
So, I just talked to Quallini and JeTSkY (in representation of Domik), and they both support the idea of a timeline, and need to check with Nezos if this can be done.

If it gets approved I'd need some help brainstorming for the following things:

- I want to make it **simple to add and remove content**
  - I don't want to update any code for a simple addition/removal of a time-point
  - Nor do I want to have to submit a PR if some Text is wrong
- **Data storage**
  - Where to store those entries?
  - Translation files are not an option, since they require work on our end to change stuff
  - Keep in mind that this will also be a multi-language feature!
  - Ideally, I'd like to keep the points in a spreadsheet like this

![2xuxx5z 1](https://user-images.githubusercontent.com/40218022/42880338-36db8082-8a94-11e8-9699-ce810ada55a5.png)
 You could even use the second column for selecting an icon or stuff like that

So please.. **Help me brainstorm!**

**Comment by aytic** [comment]
What about rendering those graphics using LaTeX. Would only require text changes once we set it up.

**Comment by HDenizD** [comment]
I can develop this if needed, i also can add some fancy animations like "on view slide in from right/left/up/down" or something.

**Comment by kellerrennkadse** [comment]
Go for it. Currently my time is more than limited

**Comment by HDenizD** [comment]
do you have some png´s for the icons and stuff for me?

**Comment by NLDev** [comment]
@HDenizD Is this still a thing?

**Comment by HDenizD** [comment]
Unfortunatly i have no Internet till 04.10. My Internet Provider sucks, i
am really sorry, i cant work on that atm.

NullDev (Chris) <notifications@github.com> schrieb am Sa., 25. Aug. 2018,
21:13:

**Comment by Fr3shlama** [comment]
I have forked the repo and added a simple timeline.

**Comment by Pacerino** [comment]
The question now is: Is this issue still open or can this be closed? I think the PR want some new stuff on the website. But nice to know!

**Comment by kellerrennkadse** [comment]
I think we could merge it.. @Fr3shlama please open a pull request to merge it in.
If we need it in the future we can enable it, if not.. Dead code isn't that bad

**Comment by Pacerino** [comment]
I would wait until we have a solution for the Domain. The PR said the have some major updates for us.

**Comment by kellerrennkadse** [comment]
I should check in on discord again xD

**Comment by Pacerino** [comment]
Yes you should! 😄

**Comment by Fr3shlama** [comment]
I kinda did open a pull request, i have no clue why you guys wont merge

**Comment by Pacerino** [comment]
Not sure if you know the currently situation: rn nobody from the programming team is doing anything. From our side the website is on hold. We need to wait for the PR and the overall coordination about the opinion what todo.

**Comment by Fr3shlama** [comment]
I was unaware of that..

Is there any chanche I could get an invite to the discord server?

**Comment by Pacerino** [comment]
The Savetheinternet Discord is open for everyone, there you go: https://discord.gg/tzRbmGp

**Comment by Fr3shlama** [comment]
I should learn to express myself better..

I am already a member of "Save my neuland", i just thought there would be a specific discord for the developers

**Comment by NLDev** [comment]
There is indeed a separate discord, however we are not in search for new developers as of now (as stated on the SaveTheInternet discord). Once that changes, we will announce it on the Discord you are already part of. There is a lot of internal restructuring going on currently.
