### ISSUE TITLE
twitter icon 

### ISSUE THREAD

**Issue by heynorris** [savetheinternetinfo/website#77]
Die Verlinkung zu unserem Account bei Twitter ist auf der alten Website immer noch die alte. Bitte auf den neuen ```https://twitter.com/DeleteArt13```  Account weiterleiten!

**Comment by heynorris** [comment]
Hat sich erledigt erstmal.

**Comment by Pacerino** [comment]
Bitte entferne den Inhalt deiner Issue nicht. Sollte die Issue nicht mehr relevant sein bitte begründen und schließen. Nur für das nächste Mal 😃
