### ISSUE TITLE
Press Releases not working

### ISSUE THREAD

**Issue by kellerrennkadse** [savetheinternetinfo/website#93]
**Describe the bug**
Spreadsheet data can't be fetched from Google.

**To Reproduce**
1. Activate the Press release section
2. Open the press relase page
3. An error is shown

**Expected behavior**
Press releases are shown as a (rather ugly 🌵 ) list

**Affected systems**
All

**Additional context**
It seems like something regarding the permissions of the API keys suddenly went wrong

**Comment by Pacerino** [comment]
Du hast vergessen den Pressespiegel auch wieder mit in die Navbar einzusetzen!
https://github.com/savetheinternetinfo/website/blob/develop/src/views/layout/header.ejs#L56

**Comment by NLDev** [comment]
Fixed: https://github.com/savetheinternetinfo/website/pull/106/commits/e987632d3bf3441145508b0411017f506fb0ff21
