### ISSUE TITLE
Countdown

### ISSUE THREAD

**Issue by Quallini** [savetheinternetinfo/website#99]
**Is your feature request related to a problem? Please describe.**
Hallo, wir würden uns einen Countdown auf der Webseite wünschen.

**Describe the solution you'd like**
Wäre cool, wenn man auf der Startseite so nen Countdown einbauen könnte, der ab dem 1.08. runtertickt bis zum STI action day bzw bis zur Abstimmung

**Describe alternatives you've considered**

**Additional context**
Wäre das möglich? Ich hoffe das Ticket war diesmal richtig so. Hab euch lieb :)

**Comment by NLDev** [comment]
Ist auf Dev schon mal eingebaut :) 
Und jap, der Issue passt perfekt ^^
Wir dich auch :smile_cat:

Resolved by https://github.com/savetheinternetinfo/website/pull/101

**Comment by schrej** [comment]
Das Datum wäre noch gut zu wissen gewesen.

**Comment by Quallini** [comment]
26.08.2018

**Comment by NLDev** [comment]
Added: https://github.com/savetheinternetinfo/website/pull/106/commits/3deb7b7e6e4e0ba8996d928a8e3b72c69a53f39d
